version: "3.3"

services:
  web:
    build: .
    network_mode: bridge
    ports:
      - "8080:8080"
    volumes:
      - .:/code
      - logvolume01:/var/log
    links:
      - redis
  redis:
    image: redis
    restart: always
    network_mode: bridge
    ports:
      - "6379:6379"
  mongo:
    image: mongo
    restart: always
    network_mode: bridge
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  logvolume01: {}
